export {default as SvgIconClose} from './icon-close.svg';
export {default as SvgIconMenu} from './icon-menu.svg';

export {default as TruckTrinityPng} from './trinity-steelindo-truck-crop-1.jpg';
export {default as IconLogoTrinityBlack} from './icon-logo-trins.png';
export {default as IconLogoTrinityWhite} from './icon-logo-trins-white.jpg';
export {default as IconLogoTrinityTrans} from './icon-logo-trins-removebg-preview.png';
export {default as IconLogoTrinityWhiteTrans} from './icon-logo-trins-white-removebg-preview.png';
export {default as IconTrinityFactory} from './ic_steel_factory.png';
export {default as IconLogoCheck} from './ic-logo-check.png';
export {default as IconTrinityTruck} from './trinity-steelindo-truck.jpg';
export {default as IconTrinityTruckSecond} from './icon-trinity-truck-2.jpeg';
export {default as IconTrinityTruckHorizontal} from './ic-trinity-truck-3.jpeg';
export {default as IconTrinityDailyActivity} from './icon-trinity-daily-acitivy.jpg';
export {default as IconTrinityBajaRingan} from './icon_baja_ringan_tct.png';
export {default as IconTrinityHollowPlafon} from './icon-hollow-plafon.png';
export {default as IconTrinityRengBajaRingan} from './ic-reng-baja-ringan.jpg';
export {default as IconTrinityWiremesh} from './ic-wiremesh.png';
export {default as IconRengBajaRingan} from './icon-reng-baja-ringan-clean.jpeg';
